//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JarmuKolcsonzo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jarmu
    {
        public int rendszam { get; set; }
        public int kategoriaId { get; set; }
        public string tipus { get; set; }
        public string modell { get; set; }
        public int ferohely { get; set; }
        public int fogyasztas { get; set; }
        public bool elerheto { get; set; }
        public bool szervizben { get; set; }
        public System.DateTime szervizDatum { get; set; }
        public System.DateTime muszakiDatum { get; set; }
        public System.DateTime beszerzesDatum { get; set; }
    
        public virtual jarmukategoria jarmukategoria { get; set; }
    }
}
